name: Inputs
on:
  workflow_dispatch:
    inputs:
      onnx_version:
        description: 'Testing input'
        required: true

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Get version
        run: echo "Test input: ${{ parameters.onnx_version }}
        
