name: RNNR NFO
 
on:
  workflow_dispatch:
 
jobs:
  getRNNRnfo:
    name: getRNNRnfo
    runs-on: self-hosted
    steps:
      - name: get info
        run: |
          echo "n: ${{ runner.name }}"
          echo "o: ${{ runner.os }}"
          echo "l: ${{ runner.labels }}"
          echo "ne: $RUNNER_NAME"
          echo "le: $RUNNER_LABELS"
      - name: get label
        uses: embedded-community/get-runner-labels-action@v0.1.0
        id: runner-labels
        with:
          github-token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}
      - run: echo ${{ steps.runner-labels.outputs.labels }}
