name: RNNR NFO
 
on:
  workflow_dispatch:
 
jobs:
  getRNNRnfo:
    name: getRNNRnfo
    runs-on: self-hosted
    steps:
      - name: get info
        run: |
          echo "n: ${{ runner.name }}"
          echo "o: ${{ runner.os }}"
          echo "l: ${{ runner.labels }}"
          echo "ne: $RUNNER_NAME"
          echo "le: $RUNNER_LABELS"
