name: Secondary Workflow
 
on:
  schedule:
    - cron: "0/5 * * * *"
  workflow_dispatch:
   inputs:
    rocm_release:
     description: ROCm Version
     required: true
     default: '6.0.2'
    performance_reports_repo:
     description: Repository where performance reports are stored
     required: true
     default: 'ROCm/migraphx-reports'
    benchmark_utils_repo:
     description: Repository where benchmark utils are stored
     required: true
     default: "ROCm/migraphx-benchmark-utils"
    organization:
     description: Organization based on which location of files will be different
     required: true
     default: "AMD"

 
jobs:
  performance_test:
    runs-on: ubuntu-latest
    outputs:
     rocm_version: ${{ steps.get_config.outputs.rocm_version }}
     utils_repo: ${{ steps.get_config.outputs.utils_repo }}
     reports_repo: ${{ steps.get_config.outputs.reports_repo }}
     repo_org: ${{ steps.get_config.outputs.repo_org }}
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: Get config
        id: get_config
        run: |
         pwd
         cd .github/workflows
         ROCM_VERSION=$(grep 'ROCM_VERSION' config.yml | cut -d "'" -f2)
         BENCHMARK_UTILS_REPO=$(awk -F "'" '/BENCHMARK_UTILS_REPO/ {print $2}' config.yml)
         PERFORMANCE_REPORTS_REPO=$(awk '/PERFORMANCE_REPORTS_REPO:/ {print $2}' config.yml)
         ORGANIZATION_REPO=$(awk '/ORGANIZATION_REPO:/ {print $2}' config.yml)
         echo "========"
         echo "$ROCM_VERSION"
         echo "$BENCHMARK_UTILS_REPO"
         echo "$PERFORMANCE_REPORTS_REPO"
         echo "$ORGANIZATION_REPO"
         echo "========"
         echo "rocm_version=$ROCM_VERSION" >> $GITHUB_OUTPUT
         echo "utils_repo=$BENCHMARK_UTILS_REPO" >> $GITHUB_OUTPUT
         echo "reports_repo=$PERFORMANCE_REPORTS_REPO" >> $GITHUB_OUTPUT
         echo "repo_org=$ORGANIZATION_REPO" >> $GITHUB_OUTPUT
#      - name: read config
#        id: get_config
#        run: |
#         echo "here code for reading config and passing to main"
#         while IFS= read -r line; do
#          if [[ $line =~ ^\s*# || $line =~ ^\s*$ ]]; then
#           continue
#          fi
#          parameter=$(echo "$line" | cut -d ':' -f 1 | tr -d '[:space:]')
#          value=$(echo "$line" | cud -d ':' -f 2- | tr -d '[:space:]')
#          export "$parameter"="$value"
#         done < config.yml

  call_reusable:
    needs: performance_test
    uses: IgorMirosavljevicHTEC/migraphx-benchmark/.github/workflows/main_wf.yml@main
    with:
     #rocm_release: ${{ github.event.inputs.rocm_release || '${{ needs.performance_test.outputs.rocm_version }}' }}
     rocm_release: ${{ github.event.inputs.rocm_release || needs.performance_test.outputs.rocm_version }}
     performance_reports_repo: ${{ github.event.inputs.performance_reports_repo || needs.performance_test.outputs.reports_repo }}
     benchmark_utils_repo: ${{ github.event.inputs.benchmark_utils_repo || needs.performance_test.outputs.utils_repo }}
     organization: ${{ github.event.inputs.organization || needs.performance_test.outputs.repo_org }}

        
