name: Test inputs
on:
  workflow_call:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: use template
        uses: ./.github/workflows/inputs.yaml
        with:
          onnx_version: ${{ github.event.inputs.onnx_version }}
      - name: get value
        run: echo "value is: ${{ github.event.inputs.onnx_version }}"
