name: Test inputs
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Test input read'
        required: true
        default: ${{ readFile('inputs.yaml') }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Input value
        run: |
          echo 'Check input value: ${{ github.event.inputs.version }}'
        
