name: Test inputs
on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        
      - name: use template
        id: template
        uses: ./.github/workflows/inputs.yaml
        with:
          onnx_version: ${{ github.event.inputs.onnx_version }}
          
      - name: get value
        run: |
          echo "value is: ${{ steps.template.outputs.onnx_version }}"
        
