name: Update file

on:
  workflow_dispatch:

jobs:
  UpdateFile:
    name: Update file test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: get_date
        run: echo todays_date="$(date +'%Y-%m-%d')" >> $GITHUB_ENV
 
      - name: extract_sha1 
        run: echo rocmlirsha="$(git ls-remote https://github.com/ROCm/rocMLIR.git develop | awk '{print $1}')" >> $GITHUB_ENV
      
      - name: Update
        run: |
          pwd
          ls -l requirements.txt
          sed -i "s/ROCm\/rocMLIR@[^ ]*/ROCmSoftwarePlatform\/rocMLIR@${{ env.rocmlirsha }}/g" requirements.txt
          ls -l requirements.txt
          cat requirements.txt
      
      - name: sudo test
        run: |
          echo "Test sudo"
          sudo rocm-smi --device 6 --setsrange 700 800 --autorespond y

      - name: test GH vars
        run: |
          echo "REPO: $GITHUB_REPOSITORY"
          echo "RUN: $GITHUB_RUN_ID"
        
          
