name: rocMLIR main weekly sync

on:
  schedule:
    #- cron: '10 17 * * 5'
    - cron: '*/5 * * * *'
  workflow_dispatch:
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  createPullRequest:
    name: Update and create pull request
    runs-on: self-hosted
    steps:
      - name: get_date
        if: ${{ github.event_name != 'pull_request' }}
        run: echo todays_date="$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: extract_sha1 
        if: ${{ github.event_name != 'pull_request' }}
        run: echo rocmlirsha="$(git ls-remote https://github.com/ROCm/rocMLIR.git develop | awk '{print $1}')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4.1.1
        
      - name: update_file
        if: ${{ github.event_name != 'pull_request' }}
        run:  |
          sed -i "s/ROCm\/rocMLIR@[^ ]*/ROCm\/rocMLIR@${{ env.rocmlirsha }}/g" requirements.txt
          cat requirements.txt

      - name: Make changes to pull request
        if: ${{ github.event_name != 'pull_request' }}
        uses: peter-evans/create-pull-request@v6.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update rocMLIR main ${{ env.rocmlirsha }}
          committer: Github <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: rocMLIR-sync-${{ env.todays_date }}
          delete-branch: true
          title: 'rocMLIR Weekly Sync ${{ env.todays_date }}'
          body: |
            Update rocMLIR version
            - Updated with changes from ${{ env.todays_date }}
            - Auto-generated by [create-pull-request][1]
            - Update requirements.txt to rocMLIR@${{ env.rocmlirsha }}

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            rocMLIR
            dependencies
            automated 
            skip bot checks
          draft: false
          base: develop

      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          ref: rocMLIR-sync-${{ env.todays_date }}
        
      - name: Checkout utils
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v4.1.1
        with:
          repository: 'IgorMirosavljevicHTEC/migraphx-benchmark-utils'
          path: migraphx-benchmark-utils
          token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}
          ref: main
          
      - name: Rebuild docker
        if: ${{ github.event_name != 'pull_request' }}
        env:
          ROCM_RELEASE: '6.0.2'
          ROCM_BASE: 'rocm/dev-ubuntu-20.04:6.0.2'
          DOCKERIMAGE: 'rocm-migraphx:6.0.2-temp'
          BUILD_NAVI: '0'
          TOKEN: ${{ secrets.MIGRAPHX_BOT_TOKEN }}
        run: |
          docker images
          cd $GITHUB_WORKSPACE/migraphx-benchmark-utils/scripts
          ./build_migraphx_docker.sh IgorMirosavljevicHTEC/migraphx-benchmark-utils
          docker images
          
      - name: Run extended accuracy test
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "start temp docker and run extended accuracy"
          
      - name: Post accuracy comment to PR
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "Post comment on PR"
          
      - name: After merge
        if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'rocMLIR-sync-')
        run: |
          echo "After merge rename docker image"
