name: rocMLIR main weekly sync

on:
#  schedule:
#    - cron: '10 17 * * 5'
  workflow_dispatch:

jobs:
  createPullRequest:
    name: Update and create pull request
    runs-on: ubuntu-latest
    steps:
      - name: get_date
        run: echo todays_date="$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: extract_sha1 
        run: echo rocmlirsha="$(git ls-remote https://github.com/ROCm/rocMLIR.git develop | awk '{print $1}')" >> $GITHUB_ENV

      - uses: actions/checkout@v4.1.1
        
      - name: update_file
        run:  |
          #cd $GITHUB_WORKSPACE
          #pwd
          #cat requirements.txt
          ls -l requirements.txt
          #chmod 777 requirements.txt
          #ls -l requirements.txt
          sed -i "s/ROCmSoftwarePlatform\/rocMLIR@[^ ]*/ROCmSoftwarePlatform\/rocMLIR@${{ env.rocmlirsha }}/g" requirements.txt
          #awk '{sub(/ROCmSoftwarePlatform\/rocMLIR@[^[:space:]]+/, "ROCmSoftwarePlatform/rocMLIR@${{ env.rocmlirsha }}",$0); print}' requirements.txt > temp_file && mv temp_file requirements.txt
          #ls -l requirements.txt
          #cat requirements.txt

      #- name: action_replace
      #  uses: Nambers/ReplaceStringInFile@v1.3
      #  with:
      #    path: ${{ github.workspace }}/requirements.txt
          # The regex of old string, which should be replaced
      #    oldString: ROCmSoftwarePlatform/rocMLIR@(/S+)  
          # Replace old string to this string
      #    newString: ROCmSoftwarePlatform/rocMLIR@${{ env.rocmlirsha }} 
          # Print out file content after replacement
      #    showFileContent: true


      - name: Make changes to pull request
        uses: peter-evans/create-pull-request@v6.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update rocMLIR main ${{ env.rocmlirsha }}
          committer: Github <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: rocMLIR-sync-${{ env.todays_date }}
          delete-branch: true
          title: 'rocMLIR Weekly Sync ${{ env.todays_date }}'
          body: |
            Update rocMLIR version
            - Updated with changes from ${{ env.todays_date }}
            - Auto-generated by [create-pull-request][1]
            - Update requirements.txt to rocMLIR@${{ env.rocmlirsha }}

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            onnxruntime
            dependencies
            automated 
            skip bot checks
          assignees: | 
            TedThemistokleous
          reviewers: |
            TedThemistokleous
          draft: false
          base: develop
